apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: kodekloud-cluster
spec:
  selector:
    matchLabels:
      app: kodekloud-cluster
  replicas: 3
  template:
    metadata:
      name: mydeployment-template
      labels:
        app: kodekloud-cluster
    spec:
      containers:
        - name: simple-webapp
          image: kodekloud/simple-webapp